install:
- source ./texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- mkdir _build
- travis_wait 3 pdflatex -output-directory _build ./LinalColloc03.tex
- travis_wait 3 pdflatex -output-directory _build ./LinalColloc03.tex
before_deploy:
- ls
deploy:
  provider: releases
  api_key:
    secure: "QZdTQVLd4D7ZjQ1XMD2r4jrQuzv87/KC0kq4I8mPXzKiDxqj/LVRDOIxKD4CVV3hHVw8zLmCFKK6SBYp6s23n89J7QMFGIx82hENJOiEPXMF4im5LEigcSHh61BbVLlFE71pITLkXH0DWLjG/wl1F7dOieU+02fpzOcdIrYf0ExDOMOpauopKm8KRzWUrv9qtMt3MP1qE7x32wpboDipnqRgAtZs46eqN/PYU9FTAVikjp1kgUWlXabTD3JFB7tLKiL+7bkx297OmOln9uExaQd76gUtnhSnnahm4c1jWPxV+BiDLZI9myXsnpzf7mHGG8IQlH+eB4aOlmVDgp7PDh6kzjR2N4amR9VXdPA4KLn50pgTr1RsrxbQQfLyHb8F7WDIbnY4SZSWoOU7SXDERiaxoZr2ex9WR/zTWyNCOSghF4oLhICx7LFI4C/XG/IzPkL7imuKm36/1IZOlNC+aYGFQUW4PSNDffVaIlzIuY8Sj843lGYR8ProPS/JoIcoVRT3jW7GhFWrTH1ezqFaN/34bV7+enZU4xE0+4cfnJ4egiZli7diDNe2iNSHZLH77tYN3b3vmqpjSLzCcgYk0Sy8N3dzQNDR5oOHxmUdT8lI4vurWupFIk54xfFuqV6XIyAyBVB5EUltE88jba6OxNyvpziy6gCnXHP8A9bgw5o="
  file: "_build/LinalColloc03.pdf"
  draft: true
  overwrite: true
  on:
    repo: bot-mne-v-rot/algebra-1course-1.5sem
    branch:  
        - master 
  skip_cleanup: 'true'